nameOverride: ""
fullnameOverride: "frontend"

replicaCount: 1

image:
  repository: vvi11iamng0/hackathon-starter-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

env:
  PORT: "3000"
  # BASE_URL: "http://localhost:3000"
  BACKEND_URL: "http://backend:8080"
  MONGODB_URI: "mongodb://mongodb.db:27017/test"

service:
  port: 3000
  targetPort: 3000
  type: NodePort

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev
  hosts:
    - paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
